export const disasterTypesSeed = [
  {
    id: 1,
    name: 'crisis del agua (sequia)',
    title: 'Crisis de Agua (Sequía)',
    description: 'La crisis del agua, o sequía, es un fenómeno natural caracterizado por una disminución significativa y prolongada en la disponibilidad de agua en una región. Esta escasez puede afectar tanto el suministro de agua potable como las fuentes de agua para la agricultura, la industria y otros usos domésticos. Las sequías pueden ser causadas por factores climáticos como la falta de precipitaciones, altas temperaturas y vientos secos, así como por la sobreexplotación de recursos hídricos. Sus consecuencias incluyen la reducción de cultivos, la pérdida de biodiversidad, problemas de salud pública y conflictos por el acceso al agua.',
    icon: 'no-water',
    imageUrl: 'https://cdn1.infocasas.com.uy/repo/img/587e5ef2bdc4d_infocdn__agua-portada.jpg',
  },
  {
    id: 2,
    name: 'desborde de rio',
    title: 'Desbordamiento de Río',
    description: 'El desborde de río se produce cuando el caudal de un río excede su capacidad de contención, provocando que el agua se desborde de sus márgenes y se extienda sobre áreas adyacentes. Este fenómeno suele estar asociado a lluvias intensas, rápidos deshielos o bloqueos naturales o artificiales que impiden el flujo normal del agua. Las inundaciones resultantes pueden causar daños considerables a viviendas, cultivos, infraestructuras y ecosistemas, además de poner en riesgo la vida de las personas y animales que habitan en las zonas ribereñas.',
    icon: 'overflow',
    imageUrl: 'https://i0.wp.com/amun.bo/wp-content/uploads/2024/01/Choqueyapu.jpg',
  },
  {
    id: 3,
    name: 'derrumbe',
    title: 'Derrumbe',
    description: 'Un derrumbe es un tipo de desastre geológico que ocurre cuando una masa de tierra, rocas o escombros se desplaza de manera súbita y violenta, generalmente por la inestabilidad del terreno. Este fenómeno puede ser provocado por factores naturales como lluvias intensas, terremotos, erupciones volcánicas o la erosión del suelo, así como por actividades humanas como la minería, la construcción o la deforestación. Los derrumbes pueden causar daños significativos a infraestructuras, viviendas y carreteras, además de representar un grave riesgo para la vida humana y animal en las áreas afectadas.',
    icon: 'landslide',
    imageUrl: 'https://www.noticiasfides.com/images/news/2024/01/c-desplome-de-plataforma-en-la-avenida-20-de-octubre_1704980110.jpg',
  },
  {
    id: 4,
    name: 'deslizamiento',
    title: 'Deslizamiento de Tierra',
    description: 'Un deslizamiento de tierra es el movimiento masivo y rápido de suelo, rocas y escombros cuesta abajo bajo la influencia de la gravedad. Este tipo de desastre suele ocurrir en áreas montañosas o inclinadas y puede ser desencadenado por precipitaciones excesivas, terremotos, actividad volcánica, deforestación o la construcción inadecuada en terrenos inestables. Los deslizamientos pueden sepultar comunidades, bloquear ríos creando lagunas peligrosas y destruir infraestructuras como carreteras y puentes, además de causar pérdidas humanas significativas.',
    icon: 'landslide',
    imageUrl: 'https://i0.wp.com/ahorainfo.com.ar/wp-content/uploads/2019/05/Momento-Inmaculada-Concepcion-Pedro-Laguna_LRZIMA20190501_0003_3.jpg',
  },
  {
    id: 5,
    name: 'granizada',
    title: 'Granizada',
    description: 'La granizada es un fenómeno meteorológico que se caracteriza por la caída de bolas de hielo, conocidas como granizo, desde las nubes durante tormentas eléctricas intensas. El tamaño y la frecuencia del granizo pueden variar, y en casos extremos, puede causar daños considerables a cultivos agrícolas, vehículos, edificaciones y otras infraestructuras. Además, las granizadas pueden representar un riesgo para la seguridad de las personas y los animales, especialmente cuando ocurren de manera repentina y en áreas densamente pobladas.',
    icon: 'hailstorm',
    imageUrl: 'https://www.la-razon.com/wp-content/uploads/2020/11/19-282.jpg',
  },
  {
    id: 6,
    name: 'inundacion',
    title: 'Inundación',
    description: 'La inundación es un evento natural en el que el agua cubre áreas que normalmente están secas, ya sea de manera temporal o prolongada. Las inundaciones pueden ser causadas por lluvias intensas, desbordes de ríos, tsunamis, marejadas ciclónicas o fallos en infraestructuras de contención como diques y presas. Este desastre puede tener efectos devastadores en comunidades, provocando la destrucción de viviendas, cultivos, infraestructura, así como la pérdida de vidas humanas y animales. Además, las inundaciones pueden facilitar la propagación de enfermedades y contaminar fuentes de agua potable.',
    icon: 'flood',
    imageUrl: 'https://www.infodiez.com/wp-content/uploads/2016/12/inundacionesenlapaz_infodiez.jpg',
  },
  {
    id: 7,
    name: 'riada',
    title: 'Riada',
    description: 'Una riada es una crecida rápida y violenta de un río, generalmente causada por lluvias intensas, deshielos rápidos o bloqueos que impiden el flujo normal del agua. A diferencia de las inundaciones graduales, las riadas se desarrollan de manera súbita, dejando poco tiempo para la evacuación y aumentando el riesgo de daños materiales y pérdidas humanas. Las riadas pueden causar el colapso de infraestructuras, la destrucción de puentes y carreteras, y afectar gravemente a las comunidades ribereñas, además de interrumpir el suministro de servicios básicos como agua, electricidad y comunicaciones.',
    icon: 'stream',
    imageUrl: 'https://www.la-razon.com/wp-content/uploads/2024/03/04/03/RIO-ARUNTAYA-RRSS.jpg',
  },
  {
    id: 8,
    name: 'incendios forestales',
    title: 'Incendios Forestales',
    description: 'Las condiciones secas provocadas por las sequías asociadas a El Niño aumentan el riesgo de incendios forestales en áreas vulnerables, destruyendo grandes extensiones de vegetación y poniendo en peligro a las poblaciones.',
    icon: 'forest-burn',
    imageUrl: 'https://www.eldiario.net/portal/wp-content/uploads/2022/09/Fuego-FOTO-696x392.jpg',
  },
  {
    id: 10,
    name: 'huracanes y ciclones tropicales',
    title: 'Huracanes y Ciclones Tropicales',
    description: 'El Niño puede alterar los patrones de formación de huracanes y ciclones. En el Pacífico oriental, la actividad ciclónica aumenta, mientras que en el Atlántico la actividad de huracanes tiende a disminuir.',
    icon: 'hurricane',
    imageUrl: 'https://services.meteored.com/img/article/los-huracanes-de-categoria-5-mas-fuertes-de-la-historia-de-allen-a-katrina-1728508034267_512.jpeg',
  },
  {
    id: 11,
    name: 'ondas de calor',
    title: 'Olas de Calor',
    description: 'Las condiciones secas y cálidas asociadas a El Niño pueden llevar a episodios de calor extremo, afectando la salud pública, la agricultura y el consumo de energía.',
    icon: 'heat-wave',
    imageUrl: 'https://hoypyspace.sfo2.cdn.digitaloceanspaces.com/imagenes/2023/09/OLA-DE-CALOR.jpg',
  },
  {
    id: 12,
    name: 'alteraciones en la pesca y ecosistemas marinos',
    title: 'Alteraciones en la Pesca y Ecosistemas Marinos',
    description: 'El calentamiento de las aguas del océano Pacífico durante El Niño afecta los ecosistemas marinos, alterando la disponibilidad de recursos pesqueros y causando mortalidad en especies marinas sensibles.',
    icon: 'fishing',
    imageUrl: 'https://talcualdigital.com/wp-content/uploads/2023/04/Diseno-sin-titulo-7-960x640.png',
  },
  {
    id: 13,
    name: 'tormentas eléctricas y granizo',
    title: 'Tormentas Eléctricas y Granizo',
    description: 'Las anomalías climáticas asociadas a El Niño pueden intensificar las tormentas eléctricas y dar lugar a tormentas severas de granizo, que pueden dañar cultivos, viviendas y vehículos.',
    icon: 'thunderstorm',
    imageUrl: 'https://www.urgente.bo/sites/default/files/la%20paz%201.jpg',
  },
  {
    id: 14,
    name: 'desabastecimiento de agua',
    title: 'Desabastecimiento de Agua',
    description: 'La combinación de sequías prolongadas y una mala gestión de los recursos hídricos durante El Niño puede provocar crisis de agua potable, afectando tanto a las comunidades urbanas como rurales.',
    icon: 'faucet',
    imageUrl: 'http://cd1.eju.tv/wp-content/uploads/2016/11/5833766bd3a57.jpg',
  }
]
