const icons = [
  "about",
  "black-cat-statue",
  "briefcase",
  "category",
  "contact-notebook",
  "contact",
  "crystal-ball"    ,
  "date",
  "emergency-kit",
  "engineer",
  "facebook",
  "faucet",
  "fishing",
  "forest-burn",
  "github",
  "google",
  "heat-wave",
  "history",
  "home",
  "hurricane",
  "instagram",
  "landslide",
  "linkedin",
  "luggage-insurance",
  "mail",
  "message",
  "mitigations",
  "no-water",
  "profile",
  "rain",
  "rocket",
  "scientist",
  "send",
  "shield",
  "starfall",
  "stock-out",
  "storm",
  "thunderstorm",
  "toucan-tropical",
  "twitch",
  "view-hide",
  "view-show",
  "x"
]

export const ourIconsSeed = icons.map( ( name, id ) => ({ id, name }) )
